lb_vip: "192.168.3.128"
lb_master: opir1-01
lb_backup: opir1-02

master_hostname: k8s-master

token: udy29x.ugyyk3tumg27atmr
podnet: 10.244.0.0/16

docker_version: "18.06.3~ce~3-0~ubuntu"

kubernetes_package_version: "1.13.4-00"

kubernetes_version: "v1.13.4"

flannel_version: "v0.11.0"
# v0.10.0
# v0.9.1
# v0.9.0
# v0.8.0
# v0.7.1
# v0.7.0
