---
- name: Add the br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Pass bridged IPv4 traffic to iptables' chains
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present

- name: Add Google Cloud Repo Key
  apt_key: 
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg 
    state: present

- name: Add docker apt key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_lsb.id|lower }}/gpg
    state: present

- name: Add docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/{{ ansible_lsb.id|lower }} {{ ansible_lsb.codename|lower }} stable
    state: present

- name: Add Kubernetes repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Remove distro docker if present
  apt:
    name: docker.io
    state: absent
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: Install docker {{ docker_version }}
  apt:
    name: 
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2 
    - software-properties-common
    - docker-ce={{ docker_version }}
    state: present

- name: Enable docker service
  systemd:
    name: docker
    state: restarted
    enabled: true

- name: Install k8s {{ kubernetes_package_version }}
  apt:
    name: ["kubelet", "kubeadm", "kubectl"]
    state: present
    force: yes
  register: k8s_installed

- name: hold k8s packages
  command: apt-mark hold kubelet kubeadm kubectl
  when: k8s_installed.changed
