---
- name: Ensure hostname set
  hostname:
    name: "{{ inventory_hostname }}"
  when: not inventory_hostname is match('(\d{1,3}\.){3}\d{1,3}')
  register: hostname
  tags: hostname

- name: set timezone to UTC
  timezone:
    name: UTC
  register: timezone

- name: apt-get update
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes
    cache_valid_time: 86400

- name: apt-get upgrade
  apt:
    upgrade: full

- name: set master hostname in /etc/hosts
  lineinfile:
    path: /etc/hosts
    state: present
    line: "{{ lb_vip }} {{ master_hostname }}"

- name: Reboot Message
  reboot:
  when: timezone is changed
