---
- name: ensure hostname set
  hostname:
    name: "{{ inventory_hostname }}"
  when: not inventory_hostname is match('(\d{1,3}\.){3}\d{1,3}')
  register: hostname

- name: set master hostname in /etc/hosts
  lineinfile:
    path: /etc/hosts
    state: present
    line: "{{ lb_vip }} {{ master_hostname }}"

- name: set timezone to UTC
  timezone:
    name: UTC
  register: timezone

- name: apt-get update and upgrade
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes
    cache_valid_time: 86400
    upgrade: full

- name: reboot Message
  reboot:
  when: hostname is changed or timezone is changed
